// <auto-generated/>
// This file was generated by BetterVanilla.Ui.XamlGenerator.
// Do not modify this file manually.

#nullable enable

using System;
using System.Collections.Generic;
using BetterVanilla.Ui.Binding;
using BetterVanilla.Ui.Controls;
using BetterVanilla.Ui.Core;
using BetterVanilla.Ui.Helpers;
using UnityEngine;

namespace BetterVanilla.Ui.Views;

public partial class OptionsView
{
    #region View Elements

    [ViewElement("root")]
    public PanelControl root { get; private set; } = null!;

    [ViewElement("titleText")]
    public TextBlockControl titleText { get; private set; } = null!;

    [ViewElement("enableFeatureToggle")]
    public ToggleControl enableFeatureToggle { get; private set; } = null!;

    [ViewElement("volumeSlider")]
    public SliderControl volumeSlider { get; private set; } = null!;

    [ViewElement("usernameInput")]
    public InputFieldControl usernameInput { get; private set; } = null!;

    [ViewElement("saveButton")]
    public ButtonControl saveButton { get; private set; } = null!;

    [ViewElement("cancelButton")]
    public ButtonControl cancelButton { get; private set; } = null!;

    #endregion

    #region Alias Mappings

    private static readonly Dictionary<string, (string Bundle, string Prefab, Type Component)> AliasMap = new()
    {
        ["Windows/OptionsPanel"] = ("BetterVanilla.Ui.Assets.ui.bundle", "Assets/Prefabs/Windows/OptionsPanel.prefab", typeof(BetterVanilla.Ui.Controls.PanelControl)),
        ["Controls/TextBlock"] = ("BetterVanilla.Ui.Assets.ui.bundle", "Assets/Prefabs/Controls/TextBlock.prefab", typeof(BetterVanilla.Ui.Controls.TextBlockControl)),
        ["Controls/Toggle"] = ("BetterVanilla.Ui.Assets.ui.bundle", "Assets/Prefabs/Controls/Toggle.prefab", typeof(BetterVanilla.Ui.Controls.ToggleControl)),
        ["Controls/Slider"] = ("BetterVanilla.Ui.Assets.ui.bundle", "Assets/Prefabs/Controls/Slider.prefab", typeof(BetterVanilla.Ui.Controls.SliderControl)),
        ["Controls/InputField"] = ("BetterVanilla.Ui.Assets.ui.bundle", "Assets/Prefabs/Controls/InputField.prefab", typeof(BetterVanilla.Ui.Controls.InputFieldControl)),
        ["Controls/Button"] = ("BetterVanilla.Ui.Assets.ui.bundle", "Assets/Prefabs/Controls/Button.prefab", typeof(BetterVanilla.Ui.Controls.ButtonControl)),
    };

    #endregion

    protected override void InitializeComponent()
    {
        // Load and instantiate elements

        // Instantiate root
        root = InstantiateControl<PanelControl>("BetterVanilla.Ui.Assets.ui.bundle", "Assets/Prefabs/Windows/OptionsPanel.prefab", transform);
        root.Name = "root";
        root.Initialize();

        // Instantiate titleText
        titleText = InstantiateControl<TextBlockControl>("BetterVanilla.Ui.Assets.ui.bundle", "Assets/Prefabs/Controls/TextBlock.prefab", root.transform);
        titleText.Name = "titleText";
        titleText.Initialize();
        titleText.Text = "Options";

        // Instantiate enableFeatureToggle
        enableFeatureToggle = InstantiateControl<ToggleControl>("BetterVanilla.Ui.Assets.ui.bundle", "Assets/Prefabs/Controls/Toggle.prefab", root.transform);
        enableFeatureToggle.Name = "enableFeatureToggle";
        enableFeatureToggle.Initialize();
        enableFeatureToggle.Text = "Enable Feature";

        // Instantiate volumeSlider
        volumeSlider = InstantiateControl<SliderControl>("BetterVanilla.Ui.Assets.ui.bundle", "Assets/Prefabs/Controls/Slider.prefab", root.transform);
        volumeSlider.Name = "volumeSlider";
        volumeSlider.Initialize();
        volumeSlider.Text = "Volume";

        // Instantiate usernameInput
        usernameInput = InstantiateControl<InputFieldControl>("BetterVanilla.Ui.Assets.ui.bundle", "Assets/Prefabs/Controls/InputField.prefab", root.transform);
        usernameInput.Name = "usernameInput";
        usernameInput.Initialize();

        // Instantiate saveButton
        saveButton = InstantiateControl<ButtonControl>("BetterVanilla.Ui.Assets.ui.bundle", "Assets/Prefabs/Controls/Button.prefab", root.transform);
        saveButton.Name = "saveButton";
        saveButton.Initialize();
        saveButton.Text = "Save Settings";

        // Instantiate cancelButton
        cancelButton = InstantiateControl<ButtonControl>("BetterVanilla.Ui.Assets.ui.bundle", "Assets/Prefabs/Controls/Button.prefab", root.transform);
        cancelButton.Name = "cancelButton";
        cancelButton.Initialize();
        cancelButton.Text = "Cancel";

        // Register elements
        RegisterElement("root", root);
        RegisterElement("titleText", titleText);
        RegisterElement("enableFeatureToggle", enableFeatureToggle);
        RegisterElement("volumeSlider", volumeSlider);
        RegisterElement("usernameInput", usernameInput);
        RegisterElement("saveButton", saveButton);
        RegisterElement("cancelButton", cancelButton);

        base.InitializeComponent();
    }

    protected override void SetupBindings()
    {
        Bind("IsFeatureEnabled", enableFeatureToggle, "IsOn", BindingMode.TwoWay).AddTo(Disposables);
        Bind("Volume", volumeSlider, "Value", BindingMode.TwoWay).AddTo(Disposables);
        Bind("Username", usernameInput, "Text", BindingMode.TwoWay).AddTo(Disposables);
    }

    protected override void SetupEventHandlers()
    {
        enableFeatureToggle.ValueChanged += value => OnFeatureToggleChanged(value);
        volumeSlider.ValueChanged += value => OnVolumeChanged(value);
        usernameInput.ValueChanged += value => OnUsernameChanged(value);
        if (saveButton is IClickableControl clickablesaveButton)
        {
            clickablesaveButton.Clicked += OnSaveClicked;
        }
        if (cancelButton is IClickableControl clickablecancelButton)
        {
            clickablecancelButton.Clicked += OnCancelClicked;
        }
    }

    #region Partial Methods (implement in user code)

    partial void OnFeatureToggleChanged(bool value);
    partial void OnVolumeChanged(float value);
    partial void OnUsernameChanged(string value);
    partial void OnSaveClicked();
    partial void OnCancelClicked();

    #endregion
}
