// <auto-generated/>
// This file was generated by BetterVanilla.Ui.XamlGenerator.
// Do not modify this file manually.

#nullable enable

using System;
using System.Collections.Generic;
using BetterVanilla.Ui.Binding;
using BetterVanilla.Ui.Controls;
using BetterVanilla.Ui.Core;
using BetterVanilla.Ui.Helpers;
using UnityEngine;

namespace BetterVanilla.Ui.Views;

public partial class OptionsView
{
    #region View Elements

    [ViewElement("root")]
    public PanelControl root { get; private set; } = null!;

    [ViewElement("header")]
    public PanelControl header { get; private set; } = null!;

    [ViewElement("titleText")]
    public TextBlockControl titleText { get; private set; } = null!;

    [ViewElement("closeButton")]
    public IconButtonControl closeButton { get; private set; } = null!;

    [ViewElement("optionsScrollView")]
    public ScrollViewControl optionsScrollView { get; private set; } = null!;

    [ViewElement("enableFeatureToggle")]
    public ToggleControl enableFeatureToggle { get; private set; } = null!;

    [ViewElement("volumeSlider")]
    public SliderControl volumeSlider { get; private set; } = null!;

    [ViewElement("usernameInput")]
    public InputFieldControl usernameInput { get; private set; } = null!;

    [ViewElement("usernameInputLocker")]
    public PanelControl usernameInputLocker { get; private set; } = null!;

    [ViewElement("difficultyDropdown")]
    public DropdownControl difficultyDropdown { get; private set; } = null!;

    [ViewElement("testText1")]
    public TextBlockControl testText1 { get; private set; } = null!;

    [ViewElement("testText2")]
    public TextBlockControl testText2 { get; private set; } = null!;

    [ViewElement("testText3")]
    public TextBlockControl testText3 { get; private set; } = null!;

    [ViewElement("testText4")]
    public TextBlockControl testText4 { get; private set; } = null!;

    [ViewElement("testText5")]
    public TextBlockControl testText5 { get; private set; } = null!;

    [ViewElement("saveButton")]
    public ButtonControl saveButton { get; private set; } = null!;

    [ViewElement("cancelButton")]
    public ButtonControl cancelButton { get; private set; } = null!;

    #endregion

    #region Alias Mappings

    private static readonly Dictionary<string, (string Bundle, string Prefab, Type Component)> AliasMap = new()
    {
        ["Controls/Panel"] = ("BetterVanilla.Ui.Assets.ui.bundle", "Assets/Prefabs/Controls/Panel.prefab", typeof(BetterVanilla.Ui.Controls.PanelControl)),
        ["Panel"] = ("BetterVanilla.Ui.Assets.ui.bundle", "Assets/Prefabs/Controls/Panel.prefab", typeof(BetterVanilla.Ui.Controls.PanelControl)),
        ["Controls/TextBlock"] = ("BetterVanilla.Ui.Assets.ui.bundle", "Assets/Prefabs/Controls/TextBlock.prefab", typeof(BetterVanilla.Ui.Controls.TextBlockControl)),
        ["IconButton"] = ("BetterVanilla.Ui.Assets.ui.bundle", "Assets/Prefabs/Controls/IconButton.prefab", typeof(BetterVanilla.Ui.Controls.IconButtonControl)),
        ["ScrollView"] = ("BetterVanilla.Ui.Assets.ui.bundle", "Assets/Prefabs/Controls/ScrollView.prefab", typeof(BetterVanilla.Ui.Controls.ScrollViewControl)),
        ["Controls/Toggle"] = ("BetterVanilla.Ui.Assets.ui.bundle", "Assets/Prefabs/Controls/Toggle.prefab", typeof(BetterVanilla.Ui.Controls.ToggleControl)),
        ["Controls/Slider"] = ("BetterVanilla.Ui.Assets.ui.bundle", "Assets/Prefabs/Controls/Slider.prefab", typeof(BetterVanilla.Ui.Controls.SliderControl)),
        ["Controls/InputField"] = ("BetterVanilla.Ui.Assets.ui.bundle", "Assets/Prefabs/Controls/InputField.prefab", typeof(BetterVanilla.Ui.Controls.InputFieldControl)),
        ["Dropdown"] = ("BetterVanilla.Ui.Assets.ui.bundle", "Assets/Prefabs/Controls/Dropdown.prefab", typeof(BetterVanilla.Ui.Controls.DropdownControl)),
        ["TextBlock"] = ("BetterVanilla.Ui.Assets.ui.bundle", "Assets/Prefabs/Controls/TextBlock.prefab", typeof(BetterVanilla.Ui.Controls.TextBlockControl)),
        ["Controls/Button"] = ("BetterVanilla.Ui.Assets.ui.bundle", "Assets/Prefabs/Controls/Button.prefab", typeof(BetterVanilla.Ui.Controls.ButtonControl)),
    };

    #endregion

    protected override void InitializeComponent()
    {
        // Load and instantiate elements

        // Instantiate root
        root = InstantiateControl<PanelControl>("BetterVanilla.Ui.Assets.ui.bundle", "Assets/Prefabs/Controls/Panel.prefab", transform);
        root.Name = "root";
        root.Initialize();
        root.Orientation = Orientation.Vertical;
        root.Background = PanelControl.ParseColor("#1A1A2E");
        root.Width = 600f;
        root.Margin = Thickness.Parse("20");
        root.HorizontalAlignment = HorizontalAlignment.Left;
        root.VerticalAlignment = VerticalAlignment.Stretch;
        root.Padding = Thickness.Parse("10");
        root.Spacing = 8f;
        root.ChildAlignment = ChildAlignment.UpperCenter;
        root.ChildControlHeight = false;
        root.ChildForceExpandWidth = false;
        root.ChildForceExpandHeight = false;
        root.ApplyLayout();

        // Instantiate header
        header = InstantiateControl<PanelControl>("BetterVanilla.Ui.Assets.ui.bundle", "Assets/Prefabs/Controls/Panel.prefab", root.transform);
        header.Name = "header";
        header.Initialize();
        header.Height = 50f;
        header.HorizontalAlignment = HorizontalAlignment.Stretch;
        header.ApplyLayout();

        // Instantiate titleText
        titleText = InstantiateControl<TextBlockControl>("BetterVanilla.Ui.Assets.ui.bundle", "Assets/Prefabs/Controls/TextBlock.prefab", header.transform);
        titleText.Name = "titleText";
        titleText.Initialize();
        titleText.FontSize = 40;
        titleText.TextAlignment = TMPro.TextAlignmentOptions.MidlineLeft;
        titleText.Width = 480f;
        titleText.Height = 50f;
        titleText.Margin = Thickness.Parse("20,0,0,0");
        titleText.HorizontalAlignment = HorizontalAlignment.Left;
        titleText.ApplyLayout();

        // Instantiate closeButton
        closeButton = InstantiateControl<IconButtonControl>("BetterVanilla.Ui.Assets.ui.bundle", "Assets/Prefabs/Controls/IconButton.prefab", header.transform);
        closeButton.Name = "closeButton";
        closeButton.Initialize();
        closeButton.Source = "BetterVanilla.Ui.Assets.Images.CloseButtonIcon.png";
        closeButton.PreserveAspect = true;
        closeButton.Width = 50f;
        closeButton.Height = 50f;
        closeButton.Margin = Thickness.Parse("5");
        closeButton.HorizontalAlignment = HorizontalAlignment.Right;
        closeButton.ApplyLayout();

        // Instantiate optionsScrollView
        optionsScrollView = InstantiateControl<ScrollViewControl>("BetterVanilla.Ui.Assets.ui.bundle", "Assets/Prefabs/Controls/ScrollView.prefab", root.transform);
        optionsScrollView.Name = "optionsScrollView";
        optionsScrollView.Initialize();
        optionsScrollView.Vertical = true;
        optionsScrollView.Horizontal = false;
        optionsScrollView.Orientation = Orientation.Vertical;
        optionsScrollView.FlexibleHeight = 1f;
        optionsScrollView.HorizontalAlignment = HorizontalAlignment.Stretch;
        optionsScrollView.Padding = Thickness.Parse("5");
        optionsScrollView.Spacing = 8f;
        optionsScrollView.ChildControlHeight = false;
        optionsScrollView.ChildForceExpandWidth = false;
        optionsScrollView.ChildForceExpandHeight = false;
        optionsScrollView.ApplyLayout();

        // Instantiate enableFeatureToggle
        enableFeatureToggle = InstantiateControl<ToggleControl>("BetterVanilla.Ui.Assets.ui.bundle", "Assets/Prefabs/Controls/Toggle.prefab", optionsScrollView.ContentTransform);
        enableFeatureToggle.Name = "enableFeatureToggle";
        enableFeatureToggle.Initialize();
        enableFeatureToggle.Text = "Enable Feature";
        enableFeatureToggle.HorizontalAlignment = HorizontalAlignment.Stretch;
        enableFeatureToggle.ApplyLayout();
        enableFeatureToggle.LabelFontStyle = TMPro.FontStyles.Bold;
        enableFeatureToggle.LabelMinFontSize = 5f;
        enableFeatureToggle.LabelMaxFontSize = 50f;

        // Instantiate volumeSlider
        volumeSlider = InstantiateControl<SliderControl>("BetterVanilla.Ui.Assets.ui.bundle", "Assets/Prefabs/Controls/Slider.prefab", optionsScrollView.ContentTransform);
        volumeSlider.Name = "volumeSlider";
        volumeSlider.Initialize();
        volumeSlider.HorizontalAlignment = HorizontalAlignment.Stretch;
        volumeSlider.ApplyLayout();

        // Instantiate usernameInput
        usernameInput = InstantiateControl<InputFieldControl>("BetterVanilla.Ui.Assets.ui.bundle", "Assets/Prefabs/Controls/InputField.prefab", optionsScrollView.ContentTransform);
        usernameInput.Name = "usernameInput";
        usernameInput.Initialize();
        usernameInput.Height = 40f;
        usernameInput.HorizontalAlignment = HorizontalAlignment.Stretch;
        usernameInput.ApplyLayout();
        usernameInput.LabelTextAlignment = TMPro.TextAlignmentOptions.MidlineLeft;
        usernameInput.PlaceholderTextAlignment = TMPro.TextAlignmentOptions.MidlineLeft;

        // Instantiate usernameInputLocker
        usernameInputLocker = InstantiateControl<PanelControl>("BetterVanilla.Ui.Assets.ui.bundle", "Assets/Prefabs/Controls/Panel.prefab", usernameInput.transform);
        usernameInputLocker.Name = "usernameInputLocker";
        usernameInputLocker.Initialize();
        usernameInputLocker.Background = PanelControl.ParseColor("#FF000016");
        usernameInputLocker.Margin = Thickness.Parse("0");
        usernameInputLocker.HorizontalAlignment = HorizontalAlignment.Stretch;
        usernameInputLocker.VerticalAlignment = VerticalAlignment.Stretch;
        usernameInputLocker.ApplyLayout();

        // Instantiate anonymous TextBlock
        var _anonymousTextBlock0 = InstantiateControl<TextBlockControl>("BetterVanilla.Ui.Assets.ui.bundle", "Assets/Prefabs/Controls/TextBlock.prefab", usernameInputLocker.transform);
        _anonymousTextBlock0.Name = "_anonymousTextBlock0";
        _anonymousTextBlock0.Initialize();
        _anonymousTextBlock0.TextAlignment = TMPro.TextAlignmentOptions.Midline;
        _anonymousTextBlock0.Text = "Locked";
        _anonymousTextBlock0.TextColor = PanelControl.ParseColor("#FF0000");
        _anonymousTextBlock0.AutoSize = true;
        _anonymousTextBlock0.MinFontSize = 5;
        _anonymousTextBlock0.MaxFontSize = 50;

        // Instantiate difficultyDropdown
        difficultyDropdown = InstantiateControl<DropdownControl>("BetterVanilla.Ui.Assets.ui.bundle", "Assets/Prefabs/Controls/Dropdown.prefab", optionsScrollView.ContentTransform);
        difficultyDropdown.Name = "difficultyDropdown";
        difficultyDropdown.Initialize();
        difficultyDropdown.HorizontalAlignment = HorizontalAlignment.Stretch;
        difficultyDropdown.ApplyLayout();

        // Instantiate testText1
        testText1 = InstantiateControl<TextBlockControl>("BetterVanilla.Ui.Assets.ui.bundle", "Assets/Prefabs/Controls/TextBlock.prefab", optionsScrollView.ContentTransform);
        testText1.Name = "testText1";
        testText1.Initialize();
        testText1.Text = "Test item 1";
        testText1.Height = 40f;
        testText1.HorizontalAlignment = HorizontalAlignment.Stretch;
        testText1.ApplyLayout();

        // Instantiate testText2
        testText2 = InstantiateControl<TextBlockControl>("BetterVanilla.Ui.Assets.ui.bundle", "Assets/Prefabs/Controls/TextBlock.prefab", optionsScrollView.ContentTransform);
        testText2.Name = "testText2";
        testText2.Initialize();
        testText2.Text = "Test item 2";
        testText2.Height = 40f;
        testText2.HorizontalAlignment = HorizontalAlignment.Stretch;
        testText2.ApplyLayout();

        // Instantiate testText3
        testText3 = InstantiateControl<TextBlockControl>("BetterVanilla.Ui.Assets.ui.bundle", "Assets/Prefabs/Controls/TextBlock.prefab", optionsScrollView.ContentTransform);
        testText3.Name = "testText3";
        testText3.Initialize();
        testText3.Text = "Test item 3";
        testText3.Height = 40f;
        testText3.HorizontalAlignment = HorizontalAlignment.Stretch;
        testText3.ApplyLayout();

        // Instantiate testText4
        testText4 = InstantiateControl<TextBlockControl>("BetterVanilla.Ui.Assets.ui.bundle", "Assets/Prefabs/Controls/TextBlock.prefab", optionsScrollView.ContentTransform);
        testText4.Name = "testText4";
        testText4.Initialize();
        testText4.Text = "Test item 4";
        testText4.Height = 40f;
        testText4.HorizontalAlignment = HorizontalAlignment.Stretch;
        testText4.ApplyLayout();

        // Instantiate testText5
        testText5 = InstantiateControl<TextBlockControl>("BetterVanilla.Ui.Assets.ui.bundle", "Assets/Prefabs/Controls/TextBlock.prefab", optionsScrollView.ContentTransform);
        testText5.Name = "testText5";
        testText5.Initialize();
        testText5.Text = "Test item 5";
        testText5.Height = 40f;
        testText5.HorizontalAlignment = HorizontalAlignment.Stretch;
        testText5.ApplyLayout();

        // Instantiate saveButton
        saveButton = InstantiateControl<ButtonControl>("BetterVanilla.Ui.Assets.ui.bundle", "Assets/Prefabs/Controls/Button.prefab", root.transform);
        saveButton.Name = "saveButton";
        saveButton.Initialize();
        saveButton.Text = "Save Settings";
        saveButton.Width = 150f;
        saveButton.Height = 40f;
        saveButton.Margin = Thickness.Parse("50");
        saveButton.HorizontalAlignment = HorizontalAlignment.Center;
        saveButton.ApplyLayout();
        saveButton.LabelTextColor = PanelControl.ParseColor("#FF0000");
        saveButton.LabelAutoSize = true;
        saveButton.LabelTextMargin = LabelStyleHelper.ParseMargin("10");

        // Instantiate cancelButton
        cancelButton = InstantiateControl<ButtonControl>("BetterVanilla.Ui.Assets.ui.bundle", "Assets/Prefabs/Controls/Button.prefab", root.transform);
        cancelButton.Name = "cancelButton";
        cancelButton.Initialize();
        cancelButton.Text = "Cancel";
        cancelButton.Width = 150f;
        cancelButton.Height = 40f;
        cancelButton.HorizontalAlignment = HorizontalAlignment.Right;
        cancelButton.ApplyLayout();

        // Register elements
        RegisterElement("root", root);
        RegisterElement("header", header);
        RegisterElement("titleText", titleText);
        RegisterElement("closeButton", closeButton);
        RegisterElement("optionsScrollView", optionsScrollView);
        RegisterElement("enableFeatureToggle", enableFeatureToggle);
        RegisterElement("volumeSlider", volumeSlider);
        RegisterElement("usernameInput", usernameInput);
        RegisterElement("usernameInputLocker", usernameInputLocker);
        RegisterElement("difficultyDropdown", difficultyDropdown);
        RegisterElement("testText1", testText1);
        RegisterElement("testText2", testText2);
        RegisterElement("testText3", testText3);
        RegisterElement("testText4", testText4);
        RegisterElement("testText5", testText5);
        RegisterElement("saveButton", saveButton);
        RegisterElement("cancelButton", cancelButton);

        base.InitializeComponent();
    }

    protected override void SetupBindings()
    {
        Bind("Username", titleText, "Text", BindingMode.TwoWay).AddTo(Disposables);
        Bind("IsFeatureEnabled", titleText, "IsVisible", BindingMode.OneWay).AddTo(Disposables);
        Bind("IsFeatureEnabled", enableFeatureToggle, "IsOn", BindingMode.TwoWay).AddTo(Disposables);
        Bind("Volume", volumeSlider, "Value", BindingMode.TwoWay).AddTo(Disposables);
        Bind("Username", usernameInput, "Text", BindingMode.TwoWay).AddTo(Disposables);
        Bind("IsFeatureEnabled", usernameInputLocker, "IsVisible", BindingMode.OneWay).AddTo(Disposables);
        Bind("DifficultyOptions", difficultyDropdown, "Options", BindingMode.OneWay).AddTo(Disposables);
    }

    protected override void SetupEventHandlers()
    {
        if (closeButton is IClickableControl clickablecloseButton)
        {
            clickablecloseButton.Clicked += OnCloseClicked;
        }
        enableFeatureToggle.ValueChanged += value => OnFeatureToggleChanged(value);
        volumeSlider.ValueChanged += value => OnVolumeChanged(value);
        usernameInput.ValueChanged += value => OnUsernameChanged(value);
        difficultyDropdown.SelectedIndexChanged += value => OnDifficultyChanged(value);
        if (saveButton is IClickableControl clickablesaveButton)
        {
            clickablesaveButton.Clicked += OnSaveClicked;
        }
        if (cancelButton is IClickableControl clickablecancelButton)
        {
            clickablecancelButton.Clicked += OnCancelClicked;
        }
    }

    #region Partial Methods (implement in user code)

    partial void OnCloseClicked();
    partial void OnFeatureToggleChanged(bool value);
    partial void OnVolumeChanged(float value);
    partial void OnUsernameChanged(string value);
    partial void OnDifficultyChanged(int value);
    partial void OnSaveClicked();
    partial void OnCancelClicked();

    #endregion
}
