using System.Text;
using BetterVanilla.Ui.XamlGenerator.Models;

namespace BetterVanilla.Ui.XamlGenerator;

/// <summary>
/// Generates C# code from parsed ViewDefinition.
/// </summary>
public sealed class CodeGenerator
{
    private readonly AliasConfig _aliasConfig;
    private readonly StringBuilder _sb = new();
    private int _indent;
    private int _anonymousCounter;

    public CodeGenerator(AliasConfig aliasConfig)
    {
        _aliasConfig = aliasConfig;
    }

    public string Generate(ViewDefinition definition)
    {
        _sb.Clear();
        _indent = 0;
        _anonymousCounter = 0;

        // Header
        AppendLine("// <auto-generated/>");
        AppendLine("// This file was generated by BetterVanilla.Ui.XamlGenerator.");
        AppendLine("// Do not modify this file manually.");
        AppendLine();
        AppendLine("#nullable enable");
        AppendLine();

        // Usings
        AppendLine("using System;");
        AppendLine("using System.Collections.Generic;");
        AppendLine("using BetterVanilla.Ui.Binding;");
        AppendLine("using BetterVanilla.Ui.Controls;");
        AppendLine("using BetterVanilla.Ui.Core;");
        AppendLine("using BetterVanilla.Ui.Helpers;");
        AppendLine("using UnityEngine;");
        AppendLine();

        // Namespace
        if (!string.IsNullOrEmpty(definition.Namespace))
        {
            AppendLine($"namespace {definition.Namespace};");
            AppendLine();
        }

        // Class (no base class - user code specifies it)
        AppendLine($"public partial class {definition.TypeName}");
        AppendLine("{");
        _indent++;

        GenerateFields(definition);
        AppendLine();
        GenerateAliasMap(definition);
        AppendLine();
        GenerateInitializeComponent(definition);
        AppendLine();
        GenerateSetupBindings(definition);
        AppendLine();
        GenerateSetupEventHandlers(definition);
        AppendLine();
        GeneratePartialMethods(definition);

        _indent--;
        AppendLine("}");

        return _sb.ToString();
    }

    private void GenerateFields(ViewDefinition definition)
    {
        AppendLine("#region View Elements");
        AppendLine();

        foreach (var element in definition.NamedElements)
        {
            var componentType = ResolveComponentType(element);
            AppendLine($"[ViewElement(\"{element.Name}\")]");
            AppendLine($"public {componentType} {element.Name} {{ get; private set; }} = null!;");
            AppendLine();
        }

        AppendLine("#endregion");
    }

    private void GenerateAliasMap(ViewDefinition definition)
    {
        AppendLine("#region Alias Mappings");
        AppendLine();
        AppendLine("private static readonly Dictionary<string, (string Bundle, string Prefab, Type Component)> AliasMap = new()");
        AppendLine("{");
        _indent++;

        var processedAliases = new HashSet<string>();

        foreach (var element in definition.NamedElements)
        {
            var alias = element.Alias ?? element.TagName;
            if (processedAliases.Contains(alias))
                continue;

            processedAliases.Add(alias);

            if (_aliasConfig.Aliases.TryGetValue(alias, out var aliasDef))
            {
                var bundle = aliasDef.Bundle ?? _aliasConfig.DefaultBundle ?? "ui.bundle";
                AppendLine($"[\"{alias}\"] = (\"{bundle}\", \"{aliasDef.Prefab}\", typeof({aliasDef.Component})),");
            }
        }

        _indent--;
        AppendLine("};");
        AppendLine();
        AppendLine("#endregion");
    }

    private void GenerateInitializeComponent(ViewDefinition definition)
    {
        AppendLine("protected override void InitializeComponent()");
        AppendLine("{");
        _indent++;

        AppendLine("// Load and instantiate elements");

        if (definition.RootElement != null)
        {
            GenerateElementInstantiation(definition.RootElement, "transform", isRoot: true);
        }

        AppendLine();
        AppendLine("// Register elements");
        foreach (var element in definition.NamedElements)
        {
            AppendLine($"RegisterElement(\"{element.Name}\", {element.Name});");
        }

        AppendLine();
        AppendLine("base.InitializeComponent();");

        _indent--;
        AppendLine("}");
    }

    private void GenerateElementInstantiation(ViewElement element, string parentVar, bool isRoot = false)
    {
        // If this is the root element (View/Window/etc.), skip instantiation and just process children
        // The root element represents the view itself, not a child control
        if (isRoot && string.IsNullOrEmpty(element.Name))
        {
            foreach (var child in element.Children)
            {
                GenerateElementInstantiation(child, parentVar);
            }
            return;
        }

        var alias = element.Alias ?? element.TagName;
        var componentType = ResolveComponentType(element);

        // Determine variable name - use element name or generate anonymous name
        var isAnonymous = string.IsNullOrEmpty(element.Name);
        var varName = isAnonymous
            ? $"_anonymous{element.TagName}{_anonymousCounter++}"
            : element.Name!;

        AppendLine();
        if (isAnonymous)
        {
            AppendLine($"// Instantiate anonymous {element.TagName}");
        }
        else
        {
            AppendLine($"// Instantiate {element.Name}");
        }

        if (_aliasConfig.Aliases.TryGetValue(alias, out var aliasDef))
        {
            var bundle = aliasDef.Bundle ?? _aliasConfig.DefaultBundle ?? "ui.bundle";
            if (isAnonymous)
            {
                AppendLine($"var {varName} = InstantiateControl<{componentType}>(\"{bundle}\", \"{aliasDef.Prefab}\", {parentVar});");
            }
            else
            {
                AppendLine($"{element.Name} = InstantiateControl<{componentType}>(\"{bundle}\", \"{aliasDef.Prefab}\", {parentVar});");
            }
        }
        else
        {
            // Fallback - create empty GameObject with component
            AppendLine($"var {varName}Go = new GameObject(\"{varName}\");");
            AppendLine($"{varName}Go.transform.SetParent({parentVar}, false);");
            if (isAnonymous)
            {
                AppendLine($"var {varName} = {varName}Go.AddComponent<{componentType}>();");
            }
            else
            {
                AppendLine($"{element.Name} = {varName}Go.AddComponent<{componentType}>();");
            }
        }

        AppendLine($"{varName}.Name = \"{varName}\";");
        AppendLine($"{varName}.Initialize();");

        // Set literal properties
        foreach (var (propName, propValue) in element.LiteralProperties)
        {
            var formattedValue = FormatPropertyValue(propName, propValue);
            AppendLine($"{varName}.{propName} = {formattedValue};");
        }

        // Set layout properties
        GenerateLayoutCode(element, varName);

        // Set text style if present (for controls with labels)
        if (element.TextStyle is { HasAnyValue: true })
        {
            GenerateTextStyleCode(element.TextStyle, varName, "Label");
        }

        // Set placeholder style if present (for InputField)
        if (element.PlaceholderStyle is { HasAnyValue: true })
        {
            GenerateTextStyleCode(element.PlaceholderStyle, varName, "Placeholder");
        }

        // Process children
        // ScrollView children should be added to ContentTransform, not transform
        var childParent = element.TagName == "ScrollView"
            ? $"{varName}.ContentTransform"
            : $"{varName}.transform";
        foreach (var child in element.Children)
        {
            GenerateElementInstantiation(child, childParent);
        }
    }

    private void GenerateTextStyleCode(TextStyleInfo style, string varName, string prefix)
    {
        if (style.FontSize.HasValue)
            AppendLine($"{varName}.{prefix}FontSize = {style.FontSize.Value}f;");

        if (!string.IsNullOrEmpty(style.TextColor))
            AppendLine($"{varName}.{prefix}TextColor = PanelControl.ParseColor(\"{style.TextColor}\");");

        if (!string.IsNullOrEmpty(style.TextAlignment))
            AppendLine($"{varName}.{prefix}TextAlignment = TMPro.TextAlignmentOptions.{style.TextAlignment};");

        if (!string.IsNullOrEmpty(style.FontStyle))
            AppendLine($"{varName}.{prefix}FontStyle = TMPro.FontStyles.{style.FontStyle};");

        if (style.CharacterSpacing.HasValue)
            AppendLine($"{varName}.{prefix}CharacterSpacing = {style.CharacterSpacing.Value}f;");

        if (style.LineSpacing.HasValue)
            AppendLine($"{varName}.{prefix}LineSpacing = {style.LineSpacing.Value}f;");

        if (style.WordSpacing.HasValue)
            AppendLine($"{varName}.{prefix}WordSpacing = {style.WordSpacing.Value}f;");

        if (style.WordWrapping.HasValue)
            AppendLine($"{varName}.{prefix}WordWrapping = {style.WordWrapping.Value.ToString().ToLowerInvariant()};");

        if (!string.IsNullOrEmpty(style.TextOverflow))
            AppendLine($"{varName}.{prefix}TextOverflow = TMPro.TextOverflowModes.{style.TextOverflow};");

        if (style.RichText.HasValue)
            AppendLine($"{varName}.{prefix}RichText = {style.RichText.Value.ToString().ToLowerInvariant()};");

        if (style.AutoSize.HasValue)
            AppendLine($"{varName}.{prefix}AutoSize = {style.AutoSize.Value.ToString().ToLowerInvariant()};");

        if (style.MinFontSize.HasValue)
            AppendLine($"{varName}.{prefix}MinFontSize = {style.MinFontSize.Value}f;");

        if (style.MaxFontSize.HasValue)
            AppendLine($"{varName}.{prefix}MaxFontSize = {style.MaxFontSize.Value}f;");

        if (!string.IsNullOrEmpty(style.TextMargin))
            AppendLine($"{varName}.{prefix}TextMargin = LabelStyleHelper.ParseMargin(\"{style.TextMargin}\");");
    }

    private void GenerateLayoutCode(ViewElement element, string varName)
    {
        var layout = element.Layout;
        if (!layout.HasAnyValue)
            return;

        // Panel and ScrollView properties (Orientation)
        var isPanel = element.TagName == "Panel";
        var isScrollView = element.TagName == "ScrollView";
        var isLayoutContainer = isPanel || isScrollView;

        if (isLayoutContainer)
        {
            // Orientation must be set first to create the LayoutGroup component
            if (!string.IsNullOrEmpty(layout.Orientation))
                AppendLine($"{varName}.Orientation = Orientation.{layout.Orientation};");
        }

        // Background color (supported by Panel, ScrollView, Button, and other controls)
        var supportsBackground = element.TagName is "Panel" or "ScrollView" or "Button";
        if (supportsBackground && !string.IsNullOrEmpty(layout.Background))
        {
            AppendLine($"{varName}.Background = PanelControl.ParseColor(\"{layout.Background}\");");
        }

        if (layout.Width.HasValue)
            AppendLine($"{varName}.Width = {layout.Width.Value}f;");

        if (layout.Height.HasValue)
            AppendLine($"{varName}.Height = {layout.Height.Value}f;");

        if (layout.MinWidth.HasValue)
            AppendLine($"{varName}.MinWidth = {layout.MinWidth.Value}f;");

        if (layout.MinHeight.HasValue)
            AppendLine($"{varName}.MinHeight = {layout.MinHeight.Value}f;");

        if (layout.MaxWidth.HasValue)
            AppendLine($"{varName}.MaxWidth = {layout.MaxWidth.Value}f;");

        if (layout.MaxHeight.HasValue)
            AppendLine($"{varName}.MaxHeight = {layout.MaxHeight.Value}f;");

        if (layout.FlexibleWidth.HasValue)
            AppendLine($"{varName}.FlexibleWidth = {layout.FlexibleWidth.Value}f;");

        if (layout.FlexibleHeight.HasValue)
            AppendLine($"{varName}.FlexibleHeight = {layout.FlexibleHeight.Value}f;");

        if (!string.IsNullOrEmpty(layout.Margin))
            AppendLine($"{varName}.Margin = Thickness.Parse(\"{layout.Margin}\");");

        if (!string.IsNullOrEmpty(layout.HorizontalAlignment))
            AppendLine($"{varName}.HorizontalAlignment = HorizontalAlignment.{layout.HorizontalAlignment};");

        if (!string.IsNullOrEmpty(layout.VerticalAlignment))
            AppendLine($"{varName}.VerticalAlignment = VerticalAlignment.{layout.VerticalAlignment};");

        // LayoutGroup properties (for PanelControl and ScrollViewControl)
        if (isLayoutContainer)
        {
            if (!string.IsNullOrEmpty(layout.Padding))
                AppendLine($"{varName}.Padding = Thickness.Parse(\"{layout.Padding}\");");

            if (layout.Spacing.HasValue)
                AppendLine($"{varName}.Spacing = {layout.Spacing.Value}f;");

            if (!string.IsNullOrEmpty(layout.ChildAlignment))
                AppendLine($"{varName}.ChildAlignment = ChildAlignment.{layout.ChildAlignment};");

            if (layout.ChildControlWidth.HasValue)
                AppendLine($"{varName}.ChildControlWidth = {layout.ChildControlWidth.Value.ToString().ToLowerInvariant()};");

            if (layout.ChildControlHeight.HasValue)
                AppendLine($"{varName}.ChildControlHeight = {layout.ChildControlHeight.Value.ToString().ToLowerInvariant()};");

            if (layout.ChildForceExpandWidth.HasValue)
                AppendLine($"{varName}.ChildForceExpandWidth = {layout.ChildForceExpandWidth.Value.ToString().ToLowerInvariant()};");

            if (layout.ChildForceExpandHeight.HasValue)
                AppendLine($"{varName}.ChildForceExpandHeight = {layout.ChildForceExpandHeight.Value.ToString().ToLowerInvariant()};");

            // Panel-only property
            if (isPanel && layout.ReverseArrangement.HasValue)
                AppendLine($"{varName}.ReverseArrangement = {layout.ReverseArrangement.Value.ToString().ToLowerInvariant()};");
        }

        // Call ApplyLayout at the end to apply all changes
        AppendLine($"{varName}.ApplyLayout();");
    }

    private void GenerateSetupBindings(ViewDefinition definition)
    {
        AppendLine("protected override void SetupBindings()");
        AppendLine("{");
        _indent++;

        var hasBindings = false;

        foreach (var element in definition.NamedElements)
        {
            foreach (var (propName, binding) in element.Bindings)
            {
                hasBindings = true;
                AppendLine($"Bind(\"{binding.Path}\", {element.Name}, \"{propName}\", BindingMode.{binding.Mode}).AddTo(Disposables);");
            }
        }

        if (!hasBindings)
        {
            AppendLine("// No bindings defined");
        }

        _indent--;
        AppendLine("}");
    }

    private void GenerateSetupEventHandlers(ViewDefinition definition)
    {
        AppendLine("protected override void SetupEventHandlers()");
        AppendLine("{");
        _indent++;

        var hasEvents = false;

        foreach (var element in definition.NamedElements)
        {
            foreach (var (eventName, handlerName) in element.EventHandlers)
            {
                hasEvents = true;
                var componentType = ResolveComponentType(element);
                var valueType = GetValueTypeForComponent(componentType);

                // Handle common events
                switch (eventName)
                {
                    case "Click" or "Clicked":
                        AppendLine($"if ({element.Name} is IClickableControl clickable{element.Name})");
                        AppendLine("{");
                        _indent++;
                        AppendLine($"clickable{element.Name}.Clicked += {handlerName};");
                        _indent--;
                        AppendLine("}");
                        break;

                    case "ValueChanged":
                        if (valueType != null)
                        {
                            // We know the specific value type for this control
                            AppendLine($"{element.Name}.ValueChanged += value => {handlerName}(value);");
                        }
                        else
                        {
                            // Unknown control type - use dynamic check (but this should be rare)
                            AppendLine($"// Unknown control type: {componentType}");
                        }
                        break;

                    case "SelectedIndexChanged":
                        // DropdownControl-specific event (alias for ValueChanged)
                        if (componentType == "DropdownControl")
                        {
                            AppendLine($"{element.Name}.SelectedIndexChanged += value => {handlerName}(value);");
                        }
                        else
                        {
                            AppendLine($"// TODO: Wire up {eventName} to {handlerName}");
                        }
                        break;

                    default:
                        AppendLine($"// TODO: Wire up {eventName} to {handlerName}");
                        break;
                }
            }
        }

        if (!hasEvents)
        {
            AppendLine("// No event handlers defined");
        }

        _indent--;
        AppendLine("}");
    }

    /// <summary>
    /// Gets the value type for a known control component type.
    /// </summary>
    private static string? GetValueTypeForComponent(string componentType)
    {
        return componentType switch
        {
            "ToggleControl" => "bool",
            "SliderControl" => "float",
            "InputFieldControl" => "string",
            "DropdownControl" => "int",
            _ => null
        };
    }

    private void GeneratePartialMethods(ViewDefinition definition)
    {
        AppendLine("#region Partial Methods (implement in user code)");
        AppendLine();

        // Collect methods with their expected parameter types
        var methodSignatures = new Dictionary<string, HashSet<string?>>();

        foreach (var element in definition.NamedElements)
        {
            var componentType = ResolveComponentType(element);

            foreach (var (eventName, handlerName) in element.EventHandlers)
            {
                if (!methodSignatures.TryGetValue(handlerName, out var paramTypes))
                {
                    paramTypes = new HashSet<string?>();
                    methodSignatures[handlerName] = paramTypes;
                }

                if (eventName is "Click" or "Clicked")
                {
                    paramTypes.Add(null); // No parameter
                }
                else if (eventName == "ValueChanged")
                {
                    var valueType = GetValueTypeForComponent(componentType);
                    if (valueType != null)
                    {
                        paramTypes.Add(valueType);
                    }
                }
                else if (eventName == "SelectedIndexChanged")
                {
                    // DropdownControl-specific event - always int
                    if (componentType == "DropdownControl")
                    {
                        paramTypes.Add("int");
                    }
                }
            }
        }

        foreach (var (method, paramTypes) in methodSignatures)
        {
            foreach (var paramType in paramTypes)
            {
                if (paramType == null)
                {
                    AppendLine($"partial void {method}();");
                }
                else
                {
                    AppendLine($"partial void {method}({paramType} value);");
                }
            }
        }

        AppendLine();
        AppendLine("#endregion");
    }

    private string ResolveComponentType(ViewElement element)
    {
        var alias = element.Alias ?? element.TagName;

        if (_aliasConfig.Aliases.TryGetValue(alias, out var aliasDef))
        {
            // Return just the type name, not the full namespace
            var lastDot = aliasDef.Component.LastIndexOf('.');
            return lastDot > 0 ? aliasDef.Component[(lastDot + 1)..] : aliasDef.Component;
        }

        // Default to tag name + Control suffix
        return element.TagName.EndsWith("Control") ? element.TagName : $"{element.TagName}Control";
    }

    // Known enum properties and their C# type names
    private static readonly Dictionary<string, string> EnumProperties = new()
    {
        ["TextAlignment"] = "TMPro.TextAlignmentOptions",
        ["FontStyle"] = "TMPro.FontStyles",
        ["TextOverflow"] = "TMPro.TextOverflowModes",
        ["ContentType"] = "TMPro.TMP_InputField.ContentType",
        ["ImageType"] = "UnityEngine.UI.Image.Type",
    };

    // Known color properties that need parsing
    private static readonly HashSet<string> ColorProperties = [
        "TextColor", "Background", "Color",
        "NormalColor", "HighlightedColor", "PressedColor", "SelectedColor", "DisabledColor"
    ];

    // Known margin/vector properties that need parsing
    private static readonly HashSet<string> MarginProperties = ["TextMargin"];

    private static string FormatPropertyValue(string propName, string value)
    {
        // Check if it's a known enum property
        if (EnumProperties.TryGetValue(propName, out var enumType))
        {
            return $"{enumType}.{value}";
        }

        // Check if it's a color property (hex string like #RGB, #RRGGBB, #RRGGBBAA)
        if (ColorProperties.Contains(propName) && value.StartsWith('#'))
        {
            return $"PanelControl.ParseColor(\"{value}\")";
        }

        // Check if it's a margin/vector property
        if (MarginProperties.Contains(propName))
        {
            return $"LabelStyleHelper.ParseMargin(\"{value}\")";
        }

        // Try to parse as bool
        if (bool.TryParse(value, out var boolValue))
            return boolValue.ToString().ToLowerInvariant();

        // Try to parse as number
        if (int.TryParse(value, out var intValue))
            return intValue.ToString();

        if (float.TryParse(value, out var floatValue))
            return $"{floatValue}f";

        // String value
        return $"\"{EscapeString(value)}\"";
    }

    private static string EscapeString(string value)
    {
        return value
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("\n", "\\n")
            .Replace("\r", "\\r")
            .Replace("\t", "\\t");
    }

    private void AppendLine(string? line = null)
    {
        if (string.IsNullOrEmpty(line))
        {
            _sb.AppendLine();
            return;
        }

        _sb.Append(new string(' ', _indent * 4));
        _sb.AppendLine(line);
    }
}
