using System.Collections.Generic;
using System.Linq;
using BetterVanilla.Ui.SourceGenerator.Models;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace BetterVanilla.Ui.SourceGenerator;

/// <summary>
/// Generates C# code from parsed ViewDefinition using Roslyn SyntaxFactory.
/// </summary>
public sealed class CodeGenerator
{
    private readonly AliasConfig _aliasConfig;
    private int _anonymousCounter;

    private static readonly Dictionary<string, string> EnumProperties = new()
    {
        ["TextAlignment"] = "TMPro.TextAlignmentOptions",
        ["FontStyle"] = "TMPro.FontStyles",
        ["TextOverflow"] = "TMPro.TextOverflowModes",
        ["ContentType"] = "TMPro.TMP_InputField.ContentType",
        ["ImageType"] = "UnityEngine.UI.Image.Type",
        ["WrapMode"] = "TextureWrapMode",
        ["FilterMode"] = "FilterMode",
    };

    private static readonly HashSet<string> ColorProperties =
    [
        "TextColor", "Background", "Color",
        "NormalColor", "HighlightedColor", "PressedColor", "SelectedColor", "DisabledColor",
        "ShadowColor"
    ];

    private static readonly HashSet<string> MarginProperties = ["TextMargin"];
    private static readonly HashSet<string> ShadowDistanceProperties = ["ShadowDistance"];
    private static readonly HashSet<string> PivotProperties = ["Pivot"];

    public CodeGenerator(AliasConfig aliasConfig)
    {
        _aliasConfig = aliasConfig;
    }

    public string Generate(ViewDefinition definition)
    {
        _anonymousCounter = 0;

        var compilationUnit = CompilationUnit()
            .WithUsings(CreateUsings())
            .WithMembers(CreateNamespaceOrClass(definition))
            .WithLeadingTrivia(CreateHeaderTrivia())
            .NormalizeWhitespace();

        return compilationUnit.ToFullString();
    }

    private static SyntaxTriviaList CreateHeaderTrivia()
    {
        return TriviaList(
            Comment("// <auto-generated/>"),
            CarriageReturnLineFeed,
            Comment("// This file was generated by BetterVanilla.Ui.SourceGenerator."),
            CarriageReturnLineFeed,
            Comment("// Do not modify this file manually."),
            CarriageReturnLineFeed,
            CarriageReturnLineFeed,
            Trivia(NullableDirectiveTrivia(Token(SyntaxKind.EnableKeyword), true)),
            CarriageReturnLineFeed
        );
    }

    private static SyntaxList<UsingDirectiveSyntax> CreateUsings()
    {
        var usings = new[]
        {
            "System",
            "System.Collections.Generic",
            "BetterVanilla.Ui.Extensions",
            "BetterVanilla.Ui.Binding",
            "BetterVanilla.Ui.Controls",
            "BetterVanilla.Ui.Core",
            "BetterVanilla.Ui.Helpers",
            "UnityEngine"
        };

        return List(usings.Select(u => UsingDirective(ParseName(u))));
    }

    private SyntaxList<MemberDeclarationSyntax> CreateNamespaceOrClass(ViewDefinition definition)
    {
        var classDeclaration = CreateClassDeclaration(definition);

        if (!string.IsNullOrEmpty(definition.Namespace))
        {
            var namespaceDeclaration = FileScopedNamespaceDeclaration(ParseName(definition.Namespace))
                .WithMembers(SingletonList<MemberDeclarationSyntax>(classDeclaration));

            return SingletonList<MemberDeclarationSyntax>(namespaceDeclaration);
        }

        return SingletonList<MemberDeclarationSyntax>(classDeclaration);
    }

    private ClassDeclarationSyntax CreateClassDeclaration(ViewDefinition definition)
    {
        var members = new List<MemberDeclarationSyntax>();

        // Add fields region
        members.AddRange(CreateFieldsRegion(definition));

        // Add alias map region
        members.AddRange(CreateAliasMapRegion(definition));

        // Add InitializeComponent method
        members.Add(CreateInitializeComponentMethod(definition));

        // Add SetupBindings method
        members.Add(CreateSetupBindingsMethod(definition));

        // Add SetupEventHandlers method
        members.Add(CreateSetupEventHandlersMethod(definition));

        // Add partial methods region
        members.AddRange(CreatePartialMethodsRegion(definition));

        return ClassDeclaration(definition.TypeName)
            .WithModifiers(TokenList(Token(SyntaxKind.PublicKeyword), Token(SyntaxKind.PartialKeyword)))
            .WithMembers(List(members));
    }

    private IEnumerable<MemberDeclarationSyntax> CreateFieldsRegion(ViewDefinition definition)
    {
        var members = new List<MemberDeclarationSyntax>();

        foreach (var element in definition.NamedElements)
        {
            if (string.IsNullOrEmpty(element.Name))
                continue;

            var componentType = ResolveComponentType(element);

            var property = PropertyDeclaration(ParseTypeName(componentType), element.Name!)
                .WithModifiers(TokenList(Token(SyntaxKind.PublicKeyword)))
                .WithAccessorList(AccessorList(List([
                    AccessorDeclaration(SyntaxKind.GetAccessorDeclaration).WithSemicolonToken(Token(SyntaxKind.SemicolonToken)),
                    AccessorDeclaration(SyntaxKind.SetAccessorDeclaration)
                        .WithModifiers(TokenList(Token(SyntaxKind.PrivateKeyword)))
                        .WithSemicolonToken(Token(SyntaxKind.SemicolonToken))
                ])))
                .WithInitializer(EqualsValueClause(
                    PostfixUnaryExpression(SyntaxKind.SuppressNullableWarningExpression, LiteralExpression(SyntaxKind.NullLiteralExpression))))
                .WithSemicolonToken(Token(SyntaxKind.SemicolonToken))
                .WithAttributeLists(SingletonList(
                    AttributeList(SingletonSeparatedList(
                        Attribute(IdentifierName("ViewElement"))
                            .WithArgumentList(AttributeArgumentList(SingletonSeparatedList(
                                AttributeArgument(LiteralExpression(SyntaxKind.StringLiteralExpression, Literal(element.Name!))))))))));

            members.Add(property);
        }

        return members;
    }

    private IEnumerable<MemberDeclarationSyntax> CreateAliasMapRegion(ViewDefinition definition)
    {
        var processedAliases = new HashSet<string>();
        var initializers = new List<ExpressionSyntax>();

        foreach (var element in definition.NamedElements)
        {
            var alias = element.Alias ?? element.TagName;
            if (!processedAliases.Add(alias))
                continue;

            if (_aliasConfig.Aliases.TryGetValue(alias, out var aliasDef))
            {
                var bundle = aliasDef.Bundle ?? _aliasConfig.DefaultBundle ?? "ui.bundle";

                // Create tuple: ("alias") = ("bundle", "prefab", typeof(Component))
                var assignment = AssignmentExpression(
                    SyntaxKind.SimpleAssignmentExpression,
                    ImplicitElementAccess()
                        .WithArgumentList(BracketedArgumentList(SingletonSeparatedList(
                            Argument(LiteralExpression(SyntaxKind.StringLiteralExpression, Literal(alias)))))),
                    TupleExpression(SeparatedList([
                        Argument(LiteralExpression(SyntaxKind.StringLiteralExpression, Literal(bundle))),
                        Argument(LiteralExpression(SyntaxKind.StringLiteralExpression, Literal(aliasDef.Prefab))),
                        Argument(TypeOfExpression(ParseTypeName(aliasDef.Component)))
                    ])));

                initializers.Add(assignment);
            }
        }

        // Build the type: Dictionary<string, (string Bundle, string Prefab, Type Component)>
        var tupleType = TupleType(SeparatedList([
            TupleElement(PredefinedType(Token(SyntaxKind.StringKeyword)), Identifier("Bundle")),
            TupleElement(PredefinedType(Token(SyntaxKind.StringKeyword)), Identifier("Prefab")),
            TupleElement(IdentifierName("Type"), Identifier("Component"))
        ]));

        var dictType = GenericName("Dictionary")
            .WithTypeArgumentList(TypeArgumentList(SeparatedList(new TypeSyntax[]
            {
                PredefinedType(Token(SyntaxKind.StringKeyword)), tupleType
            })));

        // Build the initializer expression
        var objectCreation = ObjectCreationExpression(dictType)
            .WithInitializer(InitializerExpression(
                SyntaxKind.CollectionInitializerExpression,
                SeparatedList(initializers)));

        var field = FieldDeclaration(
                VariableDeclaration(dictType)
                    .WithVariables(SingletonSeparatedList(
                        VariableDeclarator("AliasMap")
                            .WithInitializer(EqualsValueClause(objectCreation)))))
            .WithModifiers(TokenList(
                Token(SyntaxKind.PrivateKeyword),
                Token(SyntaxKind.StaticKeyword),
                Token(SyntaxKind.ReadOnlyKeyword)));

        return [field];
    }

    private MethodDeclarationSyntax CreateInitializeComponentMethod(ViewDefinition definition)
    {
        var statements = new List<StatementSyntax>();

        // Generate element instantiation
        if (definition.RootElement != null)
        {
            statements.AddRange(GenerateElementInstantiation(definition.RootElement, "transform", true));
        }

        // Register elements
        var isFirstRegister = true;
        foreach (var element in definition.NamedElements)
        {
            if (string.IsNullOrEmpty(element.Name))
                continue;

            var registerStatement = ExpressionStatement(
                InvocationExpression(IdentifierName("RegisterElement"))
                    .WithArgumentList(ArgumentList(SeparatedList([
                        Argument(LiteralExpression(SyntaxKind.StringLiteralExpression, Literal(element.Name!))),
                        Argument(IdentifierName(element.Name!))
                    ]))));

            statements.Add(isFirstRegister ? WithLeadingComment(registerStatement, "Register elements") : registerStatement);
            isFirstRegister = false;
        }

        // Call base
        statements.Add(ExpressionStatement(
            InvocationExpression(
                MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression,
                    BaseExpression(),
                    IdentifierName("InitializeComponent")))));

        return MethodDeclaration(PredefinedType(Token(SyntaxKind.VoidKeyword)), "InitializeComponent")
            .WithModifiers(TokenList(Token(SyntaxKind.ProtectedKeyword), Token(SyntaxKind.OverrideKeyword)))
            .WithBody(Block(statements));
    }

    private IEnumerable<StatementSyntax> GenerateElementInstantiation(ViewElement element, string parentVar, bool isRoot = false)
    {
        var statements = new List<StatementSyntax>();

        // Skip root element if it has no name
        if (isRoot && string.IsNullOrEmpty(element.Name))
        {
            foreach (var child in element.Children)
            {
                statements.AddRange(GenerateElementInstantiation(child, parentVar));
            }
            return statements;
        }

        var alias = element.Alias ?? element.TagName;
        var componentType = ResolveComponentType(element);
        var isAnonymous = string.IsNullOrEmpty(element.Name);
        var varName = isAnonymous ? $"_anonymous{element.TagName}{_anonymousCounter++}" : element.Name!;
        var commentText = $"Instantiate {(isAnonymous ? "anonymous " : "")}{element.TagName}";

        // Instantiation
        if (_aliasConfig.Aliases.TryGetValue(alias, out var aliasDef))
        {
            var bundle = aliasDef.Bundle ?? _aliasConfig.DefaultBundle ?? "ui.bundle";

            var instantiateCall = InvocationExpression(
                    GenericName("InstantiateControl")
                        .WithTypeArgumentList(TypeArgumentList(SingletonSeparatedList<TypeSyntax>(IdentifierName(componentType)))))
                .WithArgumentList(ArgumentList(SeparatedList([
                    Argument(LiteralExpression(SyntaxKind.StringLiteralExpression, Literal(bundle))),
                    Argument(LiteralExpression(SyntaxKind.StringLiteralExpression, Literal(aliasDef.Prefab))),
                    Argument(IdentifierName(parentVar))
                ])));

            if (isAnonymous)
            {
                statements.Add(WithLeadingComment(LocalDeclarationStatement(
                    VariableDeclaration(IdentifierName("var"))
                        .WithVariables(SingletonSeparatedList(
                            VariableDeclarator(varName).WithInitializer(EqualsValueClause(instantiateCall))))), commentText));
            }
            else
            {
                statements.Add(WithLeadingComment(ExpressionStatement(
                    AssignmentExpression(SyntaxKind.SimpleAssignmentExpression,
                        IdentifierName(varName),
                        instantiateCall)), commentText));
            }
        }
        else
        {
            // Fallback - create GameObject
            var goName = $"{varName}Go";
            statements.Add(WithLeadingComment(LocalDeclarationStatement(
                VariableDeclaration(IdentifierName("var"))
                    .WithVariables(SingletonSeparatedList(
                        VariableDeclarator(goName)
                            .WithInitializer(EqualsValueClause(
                                ObjectCreationExpression(IdentifierName("GameObject"))
                                    .WithArgumentList(ArgumentList(SingletonSeparatedList(
                                        Argument(LiteralExpression(SyntaxKind.StringLiteralExpression, Literal(varName))))))))))), commentText));

            statements.Add(ExpressionStatement(
                InvocationExpression(
                        MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression,
                            MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression,
                                IdentifierName(goName),
                                IdentifierName("transform")),
                            IdentifierName("SetParent")))
                    .WithArgumentList(ArgumentList(SeparatedList([
                        Argument(IdentifierName(parentVar)),
                        Argument(LiteralExpression(SyntaxKind.FalseLiteralExpression))
                    ])))));

            var addComponentCall = InvocationExpression(
                MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression,
                    IdentifierName(goName),
                    GenericName("AddComponent")
                        .WithTypeArgumentList(TypeArgumentList(SingletonSeparatedList<TypeSyntax>(IdentifierName(componentType))))));

            if (isAnonymous)
            {
                statements.Add(LocalDeclarationStatement(
                    VariableDeclaration(IdentifierName("var"))
                        .WithVariables(SingletonSeparatedList(
                            VariableDeclarator(varName).WithInitializer(EqualsValueClause(addComponentCall))))));
            }
            else
            {
                statements.Add(ExpressionStatement(
                    AssignmentExpression(SyntaxKind.SimpleAssignmentExpression,
                        IdentifierName(varName),
                        addComponentCall)));
            }
        }

        // Set Name
        statements.Add(CreateAssignment(varName, "Name", LiteralExpression(SyntaxKind.StringLiteralExpression, Literal(varName))));

        // Initialize
        statements.Add(ExpressionStatement(
            InvocationExpression(
                MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression,
                    IdentifierName(varName),
                    IdentifierName("Initialize")))));

        // Set literal properties
        foreach (var kvp in element.LiteralProperties)
        {
            statements.Add(CreateAssignment(varName, kvp.Key, CreatePropertyValue(kvp.Key, kvp.Value)));
        }

        // Set layout properties
        statements.AddRange(GenerateLayoutStatements(element, varName));

        // Set text styles
        if (element.TextStyle != null && element.TextStyle.HasAnyValue)
        {
            statements.AddRange(GenerateTextStyleStatements(element.TextStyle, varName, "Label"));
        }

        if (element.PlaceholderStyle != null && element.PlaceholderStyle.HasAnyValue)
        {
            statements.AddRange(GenerateTextStyleStatements(element.PlaceholderStyle, varName, "Placeholder"));
        }

        // Inline event handlers for anonymous elements
        if (isAnonymous)
        {
            statements.AddRange(GenerateInlineEventHandlers(element, varName, componentType));
        }

        // Process children
        var childParent = element.TagName == "ScrollView"
            ? $"{varName}.ContentTransform"
            : $"{varName}.transform";

        foreach (var child in element.Children)
        {
            statements.AddRange(GenerateElementInstantiation(child, childParent));
        }

        return statements;
    }

    private static IEnumerable<StatementSyntax> GenerateLayoutStatements(ViewElement element, string varName)
    {
        var statements = new List<StatementSyntax>();
        var layout = element.Layout;
        var layoutGroup = element.LayoutGroup;
        var image = element.Image;
        var source = element.Source;

        var isPanel = element.TagName == "Panel";
        var isScrollView = element.TagName == "ScrollView";
        var isIconButton = element.TagName == "IconButton";
        var isImageControl = element.TagName == "Image";
        var isLayoutContainer = isPanel || isScrollView;
        var supportsImage = isPanel || isScrollView || isIconButton;

        // LayoutGroup properties
        if (isLayoutContainer && layoutGroup != null && layoutGroup.HasAnyValue)
        {
            if (!string.IsNullOrEmpty(layoutGroup.Orientation))
                statements.Add(CreateAssignment(varName, "Orientation",
                    MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression,
                        IdentifierName("Orientation"),
                        IdentifierName(layoutGroup.Orientation!))));

            if (!string.IsNullOrEmpty(layoutGroup.Padding))
                statements.Add(CreateAssignment(varName, "Padding",
                    InvocationExpression(
                            MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression,
                                IdentifierName("Thickness"),
                                IdentifierName("Parse")))
                        .WithArgumentList(ArgumentList(SingletonSeparatedList(
                            Argument(LiteralExpression(SyntaxKind.StringLiteralExpression, Literal(layoutGroup.Padding!))))))));

            if (layoutGroup.Spacing.HasValue)
                statements.Add(CreateAssignment(varName, "Spacing", CreateFloatLiteral(layoutGroup.Spacing.Value)));

            if (!string.IsNullOrEmpty(layoutGroup.ChildAlignment))
                statements.Add(CreateAssignment(varName, "ChildAlignment",
                    MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression,
                        IdentifierName("ChildAlignment"),
                        IdentifierName(layoutGroup.ChildAlignment!))));

            if (layoutGroup.ChildControlWidth.HasValue)
                statements.Add(CreateAssignment(varName, "ChildControlWidth", CreateBoolLiteral(layoutGroup.ChildControlWidth.Value)));

            if (layoutGroup.ChildControlHeight.HasValue)
                statements.Add(CreateAssignment(varName, "ChildControlHeight", CreateBoolLiteral(layoutGroup.ChildControlHeight.Value)));

            if (layoutGroup.ChildForceExpandWidth.HasValue)
                statements.Add(CreateAssignment(varName, "ChildForceExpandWidth", CreateBoolLiteral(layoutGroup.ChildForceExpandWidth.Value)));

            if (layoutGroup.ChildForceExpandHeight.HasValue)
                statements.Add(CreateAssignment(varName, "ChildForceExpandHeight", CreateBoolLiteral(layoutGroup.ChildForceExpandHeight.Value)));

            if (layoutGroup.ReverseArrangement.HasValue)
                statements.Add(CreateAssignment(varName, "ReverseArrangement", CreateBoolLiteral(layoutGroup.ReverseArrangement.Value)));
        }

        // Image properties
        if (supportsImage && image != null && image.HasAnyValue)
        {
            if (isIconButton)
            {
                if (!string.IsNullOrEmpty(image.Color))
                    statements.Add(CreateAssignment(varName, "Color", CreateColorParse(image.Color!)));

                if (image.PreserveAspect.HasValue)
                    statements.Add(CreateAssignment(varName, "PreserveAspect", CreateBoolLiteral(image.PreserveAspect.Value)));

                if (!string.IsNullOrEmpty(image.ImageType))
                    statements.Add(CreateAssignment(varName, "ImageType",
                        MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression,
                            MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression,
                                MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression,
                                    MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression,
                                        IdentifierName("UnityEngine"),
                                        IdentifierName("UI")),
                                    IdentifierName("Image")),
                                IdentifierName("Type")),
                            IdentifierName(image.ImageType!))));

                if (image.Source != null)
                {
                    statements.AddRange(GenerateSourceStatements(image.Source, varName));
                }
            }
            else
            {
                if (!string.IsNullOrEmpty(image.Color))
                    statements.Add(CreateAssignment(varName, "Background", CreateColorParse(image.Color!)));
            }
        }

        // Image.Source for standalone Image control
        if (isImageControl && source != null && source.HasAnyValue)
        {
            statements.AddRange(GenerateSourceStatements(source, varName));
        }

        // Dimensions
        if (!string.IsNullOrEmpty(layout.Width))
            statements.AddRange(GenerateDimensionStatements(varName, "Width", layout.Width!));
        if (!string.IsNullOrEmpty(layout.Height))
            statements.AddRange(GenerateDimensionStatements(varName, "Height", layout.Height!));
        if (!string.IsNullOrEmpty(layout.MinWidth))
            statements.AddRange(GenerateDimensionStatements(varName, "MinWidth", layout.MinWidth!));
        if (!string.IsNullOrEmpty(layout.MinHeight))
            statements.AddRange(GenerateDimensionStatements(varName, "MinHeight", layout.MinHeight!));
        if (!string.IsNullOrEmpty(layout.MaxWidth))
            statements.AddRange(GenerateDimensionStatements(varName, "MaxWidth", layout.MaxWidth!));
        if (!string.IsNullOrEmpty(layout.MaxHeight))
            statements.AddRange(GenerateDimensionStatements(varName, "MaxHeight", layout.MaxHeight!));

        if (layout.FlexibleWidth.HasValue)
            statements.Add(CreateAssignment(varName, "FlexibleWidth", CreateFloatLiteral(layout.FlexibleWidth.Value)));

        if (layout.FlexibleHeight.HasValue)
            statements.Add(CreateAssignment(varName, "FlexibleHeight", CreateFloatLiteral(layout.FlexibleHeight.Value)));

        if (!string.IsNullOrEmpty(layout.Margin))
            statements.Add(CreateAssignment(varName, "Margin",
                InvocationExpression(
                        MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression,
                            IdentifierName("Thickness"),
                            IdentifierName("Parse")))
                    .WithArgumentList(ArgumentList(SingletonSeparatedList(
                        Argument(LiteralExpression(SyntaxKind.StringLiteralExpression, Literal(layout.Margin!))))))));

        if (!string.IsNullOrEmpty(layout.HorizontalAlignment))
            statements.Add(CreateAssignment(varName, "HorizontalAlignment",
                MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression,
                    IdentifierName("HorizontalAlignment"),
                    IdentifierName(layout.HorizontalAlignment!))));

        if (!string.IsNullOrEmpty(layout.VerticalAlignment))
            statements.Add(CreateAssignment(varName, "VerticalAlignment",
                MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression,
                    IdentifierName("VerticalAlignment"),
                    IdentifierName(layout.VerticalAlignment!))));

        // ApplyLayout
        if (layout.HasAnyValue || (layoutGroup != null && layoutGroup.HasAnyValue))
        {
            statements.Add(ExpressionStatement(
                InvocationExpression(
                    MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression,
                        IdentifierName(varName),
                        IdentifierName("ApplyLayout")))));
        }

        return statements;
    }

    private static IEnumerable<StatementSyntax> GenerateSourceStatements(SourceInfo source, string varName)
    {
        var statements = new List<StatementSyntax>();

        if (source.PixelsPerUnit.HasValue)
            statements.Add(CreateAssignment(varName, "PixelsPerUnit", CreateFloatLiteral(source.PixelsPerUnit.Value)));

        if (!string.IsNullOrEmpty(source.Pivot))
            statements.Add(CreateAssignment(varName, "Pivot",
                InvocationExpression(
                        MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression,
                            IdentifierName("ImageLoadingHelper"),
                            IdentifierName("ParsePivot")))
                    .WithArgumentList(ArgumentList(SingletonSeparatedList(
                        Argument(LiteralExpression(SyntaxKind.StringLiteralExpression, Literal(source.Pivot!))))))));

        if (!string.IsNullOrEmpty(source.WrapMode))
            statements.Add(CreateAssignment(varName, "WrapMode",
                MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression,
                    IdentifierName("TextureWrapMode"),
                    IdentifierName(source.WrapMode!))));

        if (!string.IsNullOrEmpty(source.FilterMode))
            statements.Add(CreateAssignment(varName, "FilterMode",
                MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression,
                    IdentifierName("FilterMode"),
                    IdentifierName(source.FilterMode!))));

        if (source.GenerateMipmaps.HasValue)
            statements.Add(CreateAssignment(varName, "GenerateMipmaps", CreateBoolLiteral(source.GenerateMipmaps.Value)));

        // Set source last (SourceAssembly must be set before EmbeddedResource)
        if (!string.IsNullOrEmpty(source.EmbeddedResource))
        {
            // Set SourceAssembly to the view's assembly so embedded resources are loaded from the correct assembly
            statements.Add(CreateAssignment(varName, "SourceAssembly",
                MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression,
                    InvocationExpression(IdentifierName("GetType")),
                    IdentifierName("Assembly"))));
            statements.Add(CreateAssignment(varName, "EmbeddedResource",
                LiteralExpression(SyntaxKind.StringLiteralExpression, Literal(source.EmbeddedResource!))));
        }
        else if (!string.IsNullOrEmpty(source.Url))
            statements.Add(CreateAssignment(varName, "Url",
                LiteralExpression(SyntaxKind.StringLiteralExpression, Literal(source.Url!))));
        else if (!string.IsNullOrEmpty(source.FilePath))
            statements.Add(CreateAssignment(varName, "FilePath",
                LiteralExpression(SyntaxKind.StringLiteralExpression, Literal(source.FilePath!))));

        return statements;
    }

    private static IEnumerable<StatementSyntax> GenerateDimensionStatements(string varName, string propertyName, string value)
    {
        var (parsedValue, isPercentage) = LayoutInfo.ParseDimension(value);

        if (isPercentage)
        {
            yield return ExpressionStatement(
                InvocationExpression(
                        MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression,
                            IdentifierName(varName),
                            IdentifierName($"Set{propertyName}Percent")))
                    .WithArgumentList(ArgumentList(SingletonSeparatedList(
                        Argument(CreateFloatLiteral(parsedValue))))));
        }
        else
        {
            yield return CreateAssignment(varName, propertyName, CreateFloatLiteral(parsedValue));
        }
    }

    private static IEnumerable<StatementSyntax> GenerateTextStyleStatements(TextStyleInfo style, string varName, string prefix)
    {
        var statements = new List<StatementSyntax>();

        if (style.FontSize.HasValue)
            statements.Add(CreateAssignment(varName, $"{prefix}FontSize", CreateFloatLiteral(style.FontSize.Value)));

        if (!string.IsNullOrEmpty(style.TextColor))
            statements.Add(CreateAssignment(varName, $"{prefix}TextColor", CreateColorParse(style.TextColor!)));

        if (!string.IsNullOrEmpty(style.TextAlignment))
            statements.Add(CreateAssignment(varName, $"{prefix}TextAlignment",
                MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression,
                    MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression,
                        IdentifierName("TMPro"),
                        IdentifierName("TextAlignmentOptions")),
                    IdentifierName(style.TextAlignment!))));

        if (!string.IsNullOrEmpty(style.FontStyle))
            statements.Add(CreateAssignment(varName, $"{prefix}FontStyle",
                MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression,
                    MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression,
                        IdentifierName("TMPro"),
                        IdentifierName("FontStyles")),
                    IdentifierName(style.FontStyle!))));

        if (style.CharacterSpacing.HasValue)
            statements.Add(CreateAssignment(varName, $"{prefix}CharacterSpacing", CreateFloatLiteral(style.CharacterSpacing.Value)));

        if (style.LineSpacing.HasValue)
            statements.Add(CreateAssignment(varName, $"{prefix}LineSpacing", CreateFloatLiteral(style.LineSpacing.Value)));

        if (style.WordSpacing.HasValue)
            statements.Add(CreateAssignment(varName, $"{prefix}WordSpacing", CreateFloatLiteral(style.WordSpacing.Value)));

        if (style.WordWrapping.HasValue)
            statements.Add(CreateAssignment(varName, $"{prefix}WordWrapping", CreateBoolLiteral(style.WordWrapping.Value)));

        if (!string.IsNullOrEmpty(style.TextOverflow))
            statements.Add(CreateAssignment(varName, $"{prefix}TextOverflow",
                MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression,
                    MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression,
                        IdentifierName("TMPro"),
                        IdentifierName("TextOverflowModes")),
                    IdentifierName(style.TextOverflow!))));

        if (style.RichText.HasValue)
            statements.Add(CreateAssignment(varName, $"{prefix}RichText", CreateBoolLiteral(style.RichText.Value)));

        if (style.AutoSize.HasValue)
            statements.Add(CreateAssignment(varName, $"{prefix}AutoSize", CreateBoolLiteral(style.AutoSize.Value)));

        if (style.MinFontSize.HasValue)
            statements.Add(CreateAssignment(varName, $"{prefix}MinFontSize", CreateFloatLiteral(style.MinFontSize.Value)));

        if (style.MaxFontSize.HasValue)
            statements.Add(CreateAssignment(varName, $"{prefix}MaxFontSize", CreateFloatLiteral(style.MaxFontSize.Value)));

        if (!string.IsNullOrEmpty(style.TextMargin))
            statements.Add(CreateAssignment(varName, $"{prefix}TextMargin",
                InvocationExpression(
                        MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression,
                            IdentifierName("LabelStyleHelper"),
                            IdentifierName("ParseMargin")))
                    .WithArgumentList(ArgumentList(SingletonSeparatedList(
                        Argument(LiteralExpression(SyntaxKind.StringLiteralExpression, Literal(style.TextMargin!))))))));

        return statements;
    }

    private static IEnumerable<StatementSyntax> GenerateInlineEventHandlers(ViewElement element, string varName, string componentType)
    {
        var statements = new List<StatementSyntax>();

        foreach (var kvp in element.EventHandlers)
        {
            var eventName = kvp.Key;
            var handlerName = kvp.Value;

            switch (eventName)
            {
                case "Click":
                case "Clicked":
                    var clickableVar = $"clickable{varName}";
                    statements.Add(IfStatement(
                        IsPatternExpression(
                            IdentifierName(varName),
                            DeclarationPattern(
                                IdentifierName("IClickableControl"),
                                SingleVariableDesignation(Identifier(clickableVar)))),
                        Block(ExpressionStatement(
                            AssignmentExpression(SyntaxKind.AddAssignmentExpression,
                                MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression,
                                    IdentifierName(clickableVar),
                                    IdentifierName("Clicked")),
                                IdentifierName(handlerName))))));
                    break;

                case "ValueChanged":
                    var valueType = GetValueTypeForComponent(componentType);
                    if (valueType != null)
                    {
                        statements.Add(ExpressionStatement(
                            AssignmentExpression(SyntaxKind.AddAssignmentExpression,
                                MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression,
                                    IdentifierName(varName),
                                    IdentifierName("ValueChanged")),
                                SimpleLambdaExpression(Parameter(Identifier("value")),
                                    InvocationExpression(IdentifierName(handlerName))
                                        .WithArgumentList(ArgumentList(SingletonSeparatedList(
                                            Argument(IdentifierName("value")))))))));
                    }
                    break;

                case "SelectedIndexChanged":
                    if (componentType == "DropdownControl")
                    {
                        statements.Add(ExpressionStatement(
                            AssignmentExpression(SyntaxKind.AddAssignmentExpression,
                                MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression,
                                    IdentifierName(varName),
                                    IdentifierName("SelectedIndexChanged")),
                                SimpleLambdaExpression(Parameter(Identifier("value")),
                                    InvocationExpression(IdentifierName(handlerName))
                                        .WithArgumentList(ArgumentList(SingletonSeparatedList(
                                            Argument(IdentifierName("value")))))))));
                    }
                    break;
            }
        }

        return statements;
    }

    private MethodDeclarationSyntax CreateSetupBindingsMethod(ViewDefinition definition)
    {
        var statements = new List<StatementSyntax>();

        foreach (var element in definition.NamedElements)
        {
            if (string.IsNullOrEmpty(element.Name))
                continue;

            foreach (var kvp in element.Bindings)
            {
                var binding = kvp.Value;

                statements.Add(ExpressionStatement(
                    InvocationExpression(
                            MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression,
                                InvocationExpression(IdentifierName("Bind"))
                                    .WithArgumentList(ArgumentList(SeparatedList([
                                        Argument(LiteralExpression(SyntaxKind.StringLiteralExpression, Literal(binding.Path))),
                                        Argument(IdentifierName(element.Name!)),
                                        Argument(LiteralExpression(SyntaxKind.StringLiteralExpression, Literal(kvp.Key))),
                                        Argument(MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression,
                                            IdentifierName("BindingMode"),
                                            IdentifierName(binding.Mode)))
                                    ]))),
                                IdentifierName("AddTo")))
                        .WithArgumentList(ArgumentList(SingletonSeparatedList(
                            Argument(IdentifierName("Disposables")))))));
            }
        }

        return MethodDeclaration(PredefinedType(Token(SyntaxKind.VoidKeyword)), "SetupBindings")
            .WithModifiers(TokenList(Token(SyntaxKind.ProtectedKeyword), Token(SyntaxKind.OverrideKeyword)))
            .WithBody(Block(statements));
    }

    private MethodDeclarationSyntax CreateSetupEventHandlersMethod(ViewDefinition definition)
    {
        var statements = new List<StatementSyntax>();

        foreach (var element in definition.NamedElements)
        {
            if (string.IsNullOrEmpty(element.Name))
                continue;

            foreach (var kvp in element.EventHandlers)
            {
                var eventName = kvp.Key;
                var handlerName = kvp.Value;
                var componentType = ResolveComponentType(element);

                switch (eventName)
                {
                    case "Click":
                    case "Clicked":
                        var clickableVar = $"clickable{element.Name}";
                        statements.Add(IfStatement(
                            IsPatternExpression(
                                IdentifierName(element.Name!),
                                DeclarationPattern(
                                    IdentifierName("IClickableControl"),
                                    SingleVariableDesignation(Identifier(clickableVar)))),
                            Block(ExpressionStatement(
                                AssignmentExpression(SyntaxKind.AddAssignmentExpression,
                                    MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression,
                                        IdentifierName(clickableVar),
                                        IdentifierName("Clicked")),
                                    IdentifierName(handlerName))))));
                        break;

                    case "ValueChanged":
                        var valueType = GetValueTypeForComponent(componentType);
                        if (valueType != null)
                        {
                            statements.Add(ExpressionStatement(
                                AssignmentExpression(SyntaxKind.AddAssignmentExpression,
                                    MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression,
                                        IdentifierName(element.Name!),
                                        IdentifierName("ValueChanged")),
                                    SimpleLambdaExpression(Parameter(Identifier("value")),
                                        InvocationExpression(IdentifierName(handlerName))
                                            .WithArgumentList(ArgumentList(SingletonSeparatedList(
                                                Argument(IdentifierName("value")))))))));
                        }
                        break;

                    case "SelectedIndexChanged":
                        if (componentType == "DropdownControl")
                        {
                            statements.Add(ExpressionStatement(
                                AssignmentExpression(SyntaxKind.AddAssignmentExpression,
                                    MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression,
                                        IdentifierName(element.Name!),
                                        IdentifierName("SelectedIndexChanged")),
                                    SimpleLambdaExpression(Parameter(Identifier("value")),
                                        InvocationExpression(IdentifierName(handlerName))
                                            .WithArgumentList(ArgumentList(SingletonSeparatedList(
                                                Argument(IdentifierName("value")))))))));
                        }
                        break;

                    default:
                        // Unhandled event type - skip
                        break;
                }
            }
        }

        return MethodDeclaration(PredefinedType(Token(SyntaxKind.VoidKeyword)), "SetupEventHandlers")
            .WithModifiers(TokenList(Token(SyntaxKind.ProtectedKeyword), Token(SyntaxKind.OverrideKeyword)))
            .WithBody(Block(statements));
    }

    private IEnumerable<MemberDeclarationSyntax> CreatePartialMethodsRegion(ViewDefinition definition)
    {
        var methodSignatures = new Dictionary<string, HashSet<string?>>();

        if (definition.RootElement != null)
        {
            CollectEventHandlers(definition.RootElement, methodSignatures);
        }

        foreach (var kvp in methodSignatures)
        {
            var method = kvp.Key;
            foreach (var paramType in kvp.Value)
            {
                MethodDeclarationSyntax methodDecl;

                if (paramType == null)
                {
                    methodDecl = MethodDeclaration(PredefinedType(Token(SyntaxKind.VoidKeyword)), method)
                        .WithModifiers(TokenList(Token(SyntaxKind.PartialKeyword)))
                        .WithSemicolonToken(Token(SyntaxKind.SemicolonToken));
                }
                else
                {
                    methodDecl = MethodDeclaration(PredefinedType(Token(SyntaxKind.VoidKeyword)), method)
                        .WithModifiers(TokenList(Token(SyntaxKind.PartialKeyword)))
                        .WithParameterList(ParameterList(SingletonSeparatedList(
                            Parameter(Identifier("value")).WithType(ParseTypeName(paramType)))))
                        .WithSemicolonToken(Token(SyntaxKind.SemicolonToken));
                }

                yield return methodDecl;
            }
        }
    }

    private void CollectEventHandlers(ViewElement element, Dictionary<string, HashSet<string?>> methodSignatures)
    {
        var componentType = ResolveComponentType(element);

        foreach (var kvp in element.EventHandlers)
        {
            var eventName = kvp.Key;
            var handlerName = kvp.Value;

            if (!methodSignatures.TryGetValue(handlerName, out var paramTypes))
            {
                paramTypes = new HashSet<string?>();
                methodSignatures[handlerName] = paramTypes;
            }

            if (eventName == "Click" || eventName == "Clicked")
            {
                paramTypes.Add(null);
            }
            else if (eventName == "ValueChanged")
            {
                var valueType = GetValueTypeForComponent(componentType);
                if (valueType != null)
                {
                    paramTypes.Add(valueType);
                }
            }
            else if (eventName == "SelectedIndexChanged")
            {
                if (componentType == "DropdownControl")
                {
                    paramTypes.Add("int");
                }
            }
        }

        foreach (var child in element.Children)
        {
            CollectEventHandlers(child, methodSignatures);
        }
    }

    // Helper methods

    private static string? GetValueTypeForComponent(string componentType)
    {
        switch (componentType)
        {
            case "ToggleControl": return "bool";
            case "SliderControl": return "float";
            case "InputFieldControl": return "string";
            case "DropdownControl": return "int";
            default: return null;
        }
    }

    private string ResolveComponentType(ViewElement element)
    {
        var alias = element.Alias ?? element.TagName;

        if (_aliasConfig.Aliases.TryGetValue(alias, out var aliasDef))
        {
            var lastDot = aliasDef.Component.LastIndexOf('.');
            return lastDot > 0 ? aliasDef.Component.Substring(lastDot + 1) : aliasDef.Component;
        }

        return element.TagName.EndsWith("Control") ? element.TagName : $"{element.TagName}Control";
    }

    private static SyntaxTriviaList CreateCommentTrivia(string text)
    {
        return TriviaList(Comment($"// {text}"), CarriageReturnLineFeed);
    }

    private static StatementSyntax WithLeadingComment(StatementSyntax statement, string text)
    {
        return statement.WithLeadingTrivia(CreateCommentTrivia(text));
    }

    private static StatementSyntax CreateAssignment(string target, string property, ExpressionSyntax value)
    {
        return ExpressionStatement(
            AssignmentExpression(SyntaxKind.SimpleAssignmentExpression,
                MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression,
                    IdentifierName(target),
                    IdentifierName(property)),
                value));
    }

    private static LiteralExpressionSyntax CreateFloatLiteral(float value)
    {
        return LiteralExpression(SyntaxKind.NumericLiteralExpression, Literal(value));
    }

    private static LiteralExpressionSyntax CreateBoolLiteral(bool value)
    {
        return value
            ? LiteralExpression(SyntaxKind.TrueLiteralExpression)
            : LiteralExpression(SyntaxKind.FalseLiteralExpression);
    }

    private static InvocationExpressionSyntax CreateColorParse(string color)
    {
        return InvocationExpression(
                MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression,
                    IdentifierName("PanelControl"),
                    IdentifierName("ParseColor")))
            .WithArgumentList(ArgumentList(SingletonSeparatedList(
                Argument(LiteralExpression(SyntaxKind.StringLiteralExpression, Literal(color))))));
    }

    private static ExpressionSyntax CreatePropertyValue(string propName, string value)
    {
        if (EnumProperties.TryGetValue(propName, out var enumType))
        {
            var parts = enumType.Split('.');
            ExpressionSyntax expr = IdentifierName(parts[0]);
            for (var i = 1; i < parts.Length; i++)
            {
                expr = MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression, expr, IdentifierName(parts[i]));
            }
            return MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression, expr, IdentifierName(value));
        }

        if (ColorProperties.Contains(propName) && value.StartsWith("#"))
        {
            return CreateColorParse(value);
        }

        if (MarginProperties.Contains(propName))
        {
            return InvocationExpression(
                    MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression,
                        IdentifierName("LabelStyleHelper"),
                        IdentifierName("ParseMargin")))
                .WithArgumentList(ArgumentList(SingletonSeparatedList(
                    Argument(LiteralExpression(SyntaxKind.StringLiteralExpression, Literal(value))))));
        }

        if (ShadowDistanceProperties.Contains(propName))
        {
            return InvocationExpression(
                    MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression,
                        IdentifierName("ShadowHelper"),
                        IdentifierName("ParseDistance")))
                .WithArgumentList(ArgumentList(SingletonSeparatedList(
                    Argument(LiteralExpression(SyntaxKind.StringLiteralExpression, Literal(value))))));
        }

        if (PivotProperties.Contains(propName))
        {
            return InvocationExpression(
                    MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression,
                        IdentifierName("ImageLoadingHelper"),
                        IdentifierName("ParsePivot")))
                .WithArgumentList(ArgumentList(SingletonSeparatedList(
                    Argument(LiteralExpression(SyntaxKind.StringLiteralExpression, Literal(value))))));
        }

        if (bool.TryParse(value, out var boolValue))
            return CreateBoolLiteral(boolValue);

        if (int.TryParse(value, out var intValue))
            return LiteralExpression(SyntaxKind.NumericLiteralExpression, Literal(intValue));

        if (float.TryParse(value, out var floatValue))
            return CreateFloatLiteral(floatValue);

        return LiteralExpression(SyntaxKind.StringLiteralExpression, Literal(value));
    }
}